name: Pipeline
on:
  push:
    branches: [ main ]
env:
  APPLICATION_NAME: startupapp

jobs:
  local_training_job:
    runs-on: ubuntu-latest
    name: Job-SagemakerLocalRun
    steps:
    - uses: actions/checkout@v3
    - name: Fire SageMaker
      id: sm_train
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        PREFIX: ${{ secrets.PREFIX }}
        IAM_ROLE_NAME: ${{ secrets.IAM_ROLE_NAME }}
        GITHUB_SHA: ${{ github.sha }}
        AWS_TEST_BUCKET: ${{ secrets.AWS_TEST_BUCKET }}
      working-directory: ./src
      run: |
        pip install --no-cache-dir --upgrade awscli boto3 sagemaker sagemaker[local] joblib s3fs fsspec 
        python local_pipeline.py
        
  testci:
    runs-on: ubuntu-latest
    name: Job-VerifyPipelineArtifactsAndModel
    needs: local_training_job
    steps:
    - uses: actions/checkout@v3     
    - name: Run pytest
      id: run_tests
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        PREFIX: ${{ secrets.PREFIX }}
        IAM_ROLE_NAME: ${{ secrets.IAM_ROLE_NAME }}
        GITHUB_SHA: ${{ github.sha }}
        AWS_TEST_BUCKET: ${{ secrets.AWS_TEST_BUCKET }}
      working-directory: ./testcases
      run: | 
        pip install --no-cache-dir --upgrade awscli boto3 pandas scikit-learn pytest 
        pytest

  submit_training_job:
    runs-on: ubuntu-latest
    name: Deploy-TrainingPipeline
    needs: testci
    steps:
    - uses: actions/checkout@v3
    - name: Fire SageMaker
      id: sm_train
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        PREFIX: ${{ secrets.PREFIX }}
        IAM_ROLE_NAME: ${{ secrets.IAM_ROLE_NAME }}
        GITHUB_SHA: ${{ github.sha }}
        AWS_TEST_BUCKET: ${{ secrets.AWS_TEST_BUCKET }}
        AWS_SAGEMAKER_ROLE: ${{ secrets.AWS_SAGEMAKER_ROLE }}
      working-directory: ./src
      run: |
        pip install --no-cache-dir --upgrade awscli boto3 sagemaker joblib s3fs fsspec 
        python training_pipeline.py 

  submit_inference_job:
    runs-on: ubuntu-latest
    name: Deploy-InferencePipeline
    needs: testci
    steps:
    - uses: actions/checkout@v3
    - name: Fire SageMaker
      id: sm_train
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        PREFIX: ${{ secrets.PREFIX }}
        IAM_ROLE_NAME: ${{ secrets.IAM_ROLE_NAME }}
        GITHUB_SHA: ${{ github.sha }}
        AWS_TEST_BUCKET: ${{ secrets.AWS_TEST_BUCKET }}
        AWS_SAGEMAKER_ROLE: ${{ secrets.AWS_SAGEMAKER_ROLE }}
      working-directory: ./src
      run: |
        pip install --no-cache-dir --upgrade awscli boto3 sagemaker joblib s3fs fsspec 
        python inference_pipeline.py 

  submit_monitoring_job:
    runs-on: ubuntu-latest
    name: Deploy-MonitoringPipeline
    needs: testci
    steps:
    - uses: actions/checkout@v3
    - name: Fire SageMaker
      id: sm_train
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        PREFIX: ${{ secrets.PREFIX }}
        IAM_ROLE_NAME: ${{ secrets.IAM_ROLE_NAME }}
        GITHUB_SHA: ${{ github.sha }}
        AWS_TEST_BUCKET: ${{ secrets.AWS_TEST_BUCKET }}
        AWS_SAGEMAKER_ROLE: ${{ secrets.AWS_SAGEMAKER_ROLE }}
      working-directory: ./src
      run: |
        pip install --no-cache-dir --upgrade awscli boto3 sagemaker joblib s3fs fsspec 
        python monitoring_pipeline.py 
